library(tidyverse)
library(plotly)
other_palette <- c("#007030", "#005624", "#FEE11A", "#888888", "#cccccc")
prof_palette_1 <- c("#e9c46a", "#f4a261", "#e76f51", "#2a9d8f", "#264653")
activities_dict <- c("1" = "Browsing content", "2" = "Posting content", "3" = "Interacting with others", "4" = "Shopping", "5" = "Other Activity")
reasons_dict <- c("1" = "Similar US platforms unavailable", "2" = "Better content alignment", "3" = "Encouraged by friends/influencers", "4" = "Bypass U.S. restrictions", "5" = "Access unique products/services", "6" = "Curiosity about Chinese platforms", "7" = "Information outside US media", "8" = "Connect to international communities", "9" = "Other Reason")
Frequency <- factor(c(1, 2, 3, 4), labels = c("Rarely", "A few times per week", "Daily", "Multiple times a day"))
s_nodes <- unique(c(reasons_dict, activities_dict, as.character(Frequency)))
s_colors <- colorRampPalette(prof_palette_1)(length(s_nodes))
df <- data.frame(node = s_nodes, color = s_colors)
print(df)
